In [36]:
import numpy as np #numpy is useful for making arrays 
import pandas as pd #to make dataframes(structured table)
from sklearn.model_selection import train_test_split #to allow training data and test data
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score #to check performance of model

In [37]:
# load the dataset to a pandas dataframe
credit_card_data = pd.read_csv("../input/creditcardfraud/creditcard.csv")

In [38]:
# 1st five rows of data set
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [39]:
credit_card_data.tail() #last five rows

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [40]:
#dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [41]:
#checking the no. of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

We dont have any missing values in this dataset.

In [42]:
#check distribution of legit transactions & fraudulent transactions.
credit_card_data['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

This dataset is highly unbalanced

0 --> Normal Transaction
1 -- > Fraudulent transaction

In [43]:
 #seperating the data for analysis 
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [44]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [45]:
#statistical measures of data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [46]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

Mean for fraudulent is more

In [47]:
#compare the values for both transaction
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [48]:
#Dealing with unbalance data

UNDER-SAMPLING

Build a sample dataset containing similar distribution of normal transaction and fraudulent transactions.

Number of fraudulent transactions --> 492

In [49]:
legit_sample = legit.sample(n=492)

In [50]:
#concatenating two dataframes
new_dataset = pd.concat([legit_sample, fraud],axis=0) #axis =0 row wise axis = 1 column wise

In [51]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
157423,109864.0,0.498524,0.805833,-0.072191,-0.606075,1.164977,-0.641339,1.107714,-0.559407,1.469242,...,0.197140,1.151864,-0.168168,0.587994,-0.453893,-0.685167,-0.033449,-0.121840,1.00,0
42542,41144.0,-1.358491,-0.535583,0.503788,-0.577362,-1.351071,1.092721,1.374525,0.681414,-0.358355,...,0.154878,-0.321092,1.094902,-0.296688,-0.186652,0.706874,-0.326771,-0.076378,431.97,0
30318,35868.0,1.282416,-0.752033,-0.111368,-0.625602,-0.888735,-0.825437,-0.277074,-0.225802,-0.776425,...,-0.382390,-0.841973,-0.083583,-0.130137,0.287252,1.067461,-0.087749,0.011882,90.95,0
58914,48607.0,1.295811,0.352119,-0.136246,0.294892,0.348541,-0.061909,0.035119,-0.046544,-0.314201,...,-0.299712,-0.840974,-0.041442,-0.860466,0.378673,0.146235,-0.021146,0.011085,1.98,0
76427,56563.0,0.962629,-0.041415,0.978076,2.725878,-0.432006,0.670772,-0.308389,0.248760,-0.086368,...,-0.057063,-0.090825,-0.178263,0.016910,0.559973,0.057130,0.008915,0.023798,80.20,0

In [52]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [53]:
new_dataset['Class'].value_counts()

0    492
1    492
Name: Class, dtype: int64

In [54]:
new_dataset.groupby('Class').mean() 
#to check good sample or bad sample we have to compare it with previous data we can observe that good sample contains similar mean as compare to previous data

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,89419.542683,-0.019930,-0.024408,0.116196,0.093130,0.065805,-0.020133,0.015417,0.053338,0.014911,...,0.012973,-0.004050,-0.043194,0.029779,0.008267,-0.014721,-0.009977,-0.016188,0.007265,90.220854
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

Splitting data into features and targets

In [55]:
x = new_dataset.drop(columns = 'Class',axis=1)
y = new_dataset['Class']

In [56]:
print(x)

            Time        V1        V2        V3        V4        V5        V6  \
157423  109864.0  0.498524  0.805833 -0.072191 -0.606075  1.164977 -0.641339
42542    41144.0 -1.358491 -0.535583  0.503788 -0.577362 -1.351071  1.092721
30318    35868.0  1.282416 -0.752033 -0.111368 -0.625602 -0.888735 -0.825437
58914    48607.0  1.295811  0.352119 -0.136246  0.294892  0.348541 -0.061909
76427    56563.0  0.962629 -0.041415  0.978076  2.725878 -0.432006  0.670772
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
157423  1.107714 -0.559407  1.469242  ... -0.137459  0.197140  1.151864
42542   1.374525  0.681414 -0.358355  ...  0.611592  0.154878 -0.321092
30318  -0.277074 -0.225802 -0.776425  ... -0.346900 -0.382390 -0.841973
58914   0.035119 -0.046544 -0.314201  ...  0.038718 -0.299712 -0.840974
76427  -0.308389  0.248760 -0.086368  ... -0.010553 -0.057063 -0.090825
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
157423 -0.168168  0.587994 -0.453893 -0.685167 -0.033449 -0.121840    1.00
42542   1.094902 -0.296688 -0.186652  0.706874 -0.326771 -0.076378  431.97
30318  -0.083583 -0.130137  0.287252  1.067461 -0.087749  0.011882   90.95
58914  -0.041442 -0.860466  0.378673  0.146235 -0.021146  0.011085    1.98
76427  -0.178263  0.016910  0.559973  0.057130  0.008915  0.023798   80.20
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [57]:
print(y)

157423    0
42542     0
30318     0
58914     0
76427     0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

Split the data into training data and test data

In [58]:
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size = 0.2, stratify=y, random_state=2)

In [59]:
''' we created 4 arrays here because x and y train will store the 80% data and their
corresponding labels and x&y test will store 20% data and their corresponding labels'''

' we created 4 arrays here because x and y train will store the 80% data and their\ncorresponding labels and x&y test will store 20% data and their corresponding labels'

In [60]:
''' test size = 0.2 denotes we are taking 20% of data as our test data
stratify denotes even distribution of class between x train and x test '''

' test size = 0.2 denotes we are taking 20% of data as our test data\nstratify denotes even distribution of class between x train and x test '

In [61]:
print(x.shape,x_train.shape,x_test.shape)

(984, 30) (787, 30) (197, 30)

Model Training

Logistic Regression

In [62]:
model = LogisticRegression()

In [63]:
# training the Logistic Regression Model with Training Data
model.fit(x_train,y_train)

LogisticRegression()

Model Evaluation

Accuracy score

In [64]:
# accuracy on training data 
x_train_prediction = model.predict(x_train) #this will predict y_train values corresponding to x_train
training_data_accuracy = accuracy_score(x_train_prediction, y_train) #will compare values predicted by our model with values stored in y_train

In [65]:
print('Accuracy on training data:',training_data_accuracy)

Accuracy on training data: 0.9199491740787802

In [66]:
# accuracy on test data
x_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction, y_test)

In [67]:
print('Accuracy on Test Data:',test_data_accuracy)

Accuracy on Test Data: 0.9035532994923858